apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  selector:
    matchLabels:
      app: email-service
  replicas: 1
  template:
    metadata:
      labels:
        app: email-service
        common-label: microservice
    spec:
      containers:
      - name: email-service
        image: email-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8009