apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  selector:
    matchLabels:
      app: notifications
  replicas: 1
  template:
    metadata:
      labels:
        app: notifications
        common-label: microservice
    spec:
      containers:
      - name: notifications
        image: notifications
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8008