apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-management
spec:
  selector:
    matchLabels:
      app: product-catalog-management
  replicas: 1
  template:
    metadata:
      labels:
        app: product-catalog-management
        common-label: microservice
    spec:
      containers:
      - name: product-catalog-management
        image: product-catalog-management
        imagePullPolicy: Always
        ports:
        - containerPort: 8001